<?php

namespace Application\Repository;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return parent::findBy([], ['createdAt' => 'DESC']);
    }
}
