<?php

namespace Application\Repository;

/**
 * HashtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashtagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return parent::findBy([], ['createdAt' => 'DESC']);
    }
}
