<?php
$this->inlineScript()
    ->prependFile($this->basePath('/assets/js/common/table.list.js'))
;

$this->headScript()
    ->prependFile($this->basePath('/assets/bower_components/bootbox.js/bootbox.js'))
;
?>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="btn-group btn-group-lg pull-right" role="group" aria-label="Large button group">
                            <a href="<?php echo $this->url('hashtag/default', ['action' => 'add']);?>" class="btn bg-orange waves-effect waves-block">ADICIONAR</a>
                        </div>
                    </div>
                </div>
            </div>
<?php if (count($this->data) > 0) : ?>
            <div class="body table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th class="hidden-xs">Criado em</th>
                            <th class="hidden-xs">Atualizado em</th>
                            <th>Tempo</th>
                            <th>Nome</th>
                            <th class="text-right">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
<?php   foreach ($this->data as $entity) :?>
                        <tr>
                            <td class="hidden-xs" width="190"><?php echo $this->dateFormat($entity->getCreatedAt(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, 'pt_BR');?></td>
                            <td class="hidden-xs" width="190"><?php echo $this->dateFormat($entity->getUpdatedAt(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, 'pt_BR') ;?></td>
                            <td><?php echo $entity->getRunTimeScript();?> min.</td>
                            <td><?php echo $entity->getTag();?></td>
                            <td>
                                <div class="btn-group pull-right">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="javascript:void(0);" class="bt_action" data-url="<?php echo $this->url('hashtag/default', ['action' => 'edit', 'id' => $entity->getId()]);?>"><i class="material-icons">mode_edit</i> Editar</a>
                                            <a href="javascript:void(0);" class="bt_action_confirm_delete" data-url="<?php echo $this->url('hashtag/default', ['action' => 'delete', 'id' => $entity->getId()]);?>" data-object-delete="<?php echo $entity->getTag();?>"><i class="material-icons">delete</i> Deletar</a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
<?php   endforeach;?>
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-lg-12">
<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/layout/paginator');?>
                    </div>
                </div>
            </div>
<?php else:?>
            <div class="body">
<?php echo $this->partial('partials/layout/no_records');?>
            </div>
<?php endif; ?>
        </div>
    </div>
</div>