<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="pt-br">
    <head>
        <?php
        echo $this->headTitle('Praça Capital - Instagram')
                ->setSeparator(' / ')
                ->setAutoEscape(false)
            . PHP_EOL;
        ?>
        <!-- BEGIN META -->
        <meta charset="UTF-8" />
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            . PHP_EOL;
        ?>
        <!-- END META -->

        <!-- BEGIN STYLESHEETS -->
        <?php
        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/assets/images/favicon_pracacapital.png')])
                ->appendStylesheet($this->basePath('/assets/css/style.css'))
                ->prependStylesheet($this->basePath('/assets/bower_components/adminbsb-materialdesign/css/themes/theme-orange.min.css'))
                ->prependStylesheet($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/animate-css/animate.min.css'))
                ->prependStylesheet($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/node-waves/waves.min.css'))
                ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext')
                ->prependStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons')
                ->prependStylesheet($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/bootstrap/css/bootstrap.min.css'))
            . PHP_EOL;
        ?>
        <!-- END STYLESHEETS -->

        <!-- BEGIN JAVASCRIPT -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('/assets/js/common/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
                ->prependFile($this->basePath('/assets/js/common/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
                ->prependFile($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/jquery-slimscroll/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/node-waves/waves.min.js'))
                ->prependFile($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/bootstrap/js/bootstrap.min.js'))
                ->prependFile($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/jquery/jquery.min.js'))
            . PHP_EOL;
        ?>
        <!-- END JAVASCRIPT -->
    </head>
    <body class="theme-orange">
<?php echo $this->partial('partials/layout/flash_message.phtml');?>
        <!-- Page Loader -->
        <div class="page-loader-wrapper">
            <div class="loader">
                <div class="preloader">
                    <div class="spinner-layer pl-orange">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div>
                        <div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
                <p>Please wait...</p>
            </div>
        </div>
        <!-- #END# Page Loader -->

        <!-- Overlay For Sidebars -->
        <div class="overlay"></div>
        <!-- #END# Overlay For Sidebars -->

        <!-- Top Bar -->
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="javascript:void(0);" class="bars" style="display: none;"></a>
                    <a class="navbar-brand" href="<?php echo $this->url('home');?>">Praça Capital - Instagram</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse">

                </div>
            </div>
        </nav>
        <!-- #Top Bar -->

        <section>
            <!-- Left Sidebar -->
            <aside id="leftsidebar" class="sidebar">
                <!-- User Info -->
                <div class="user-info">
                    <div class="info-container">
                        <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?php echo ($this->zfcUserIdentity() ? $this->zfcUserIdentity()->getName() : ''); ?></div>
                        <div class="email"><?php echo ($this->zfcUserIdentity() ? $this->zfcUserIdentity()->getEmail() : ''); ?></div>
                        <div class="btn-group user-helper-dropdown">
                            <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);" class=" waves-effect waves-block"><i class="material-icons">person</i>Perfil</a></li>
                                <li role="seperator" class="divider"></li>
                                <li><a href="<?php echo $this->url('zfcuser/logout');?>" class=" waves-effect waves-block"><i class="material-icons">input</i>Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- #User Info -->

                <!-- Menu -->
                <div class="menu">
                    <div class="slimScrollDiv">
<?php echo $this->navigation('navigation')->menu()->setPartial('partials/navigation/menu'); ?>
                    </div>
                </div>
                <!-- #Menu -->

                <!-- Footer -->
                <div class="legal">
                    <div class="copyright">
                        © <?php echo date('Y');?> <a href="javascript:void(0);">Praça Capital - Instagram</a>.
                    </div>
                    <div class="version">
                        Farol Sign - Comunicação
                    </div>
                </div>
                <!-- #Footer -->
            </aside>
            <!-- #END# Left Sidebar -->
            <!-- Right Sidebar -->
            <aside id="rightsidebar" class="right-sidebar">
            </aside>
            <!-- #END# Right Sidebar -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<?php echo $this->navigation('navigation')->breadcrumbs()->setRenderInvisible(true)->setPartial('partials/navigation/breadcrumb') . PHP_EOL; ?>
<?php echo $this->content . PHP_EOL; ?>
                    </div>
                </div>
            </div>
        </section>
<?php
    echo $this->inlineScript()
            ->appendFile($this->basePath('/assets/bower_components/adminbsb-materialdesign/js/admin.js'))
        . PHP_EOL;
?>
    </body>
</html>