<?php
$this->headLink()
    ->appendStylesheet($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css'))
;

$this->headScript()
    ->prependFile($this->basePath('/assets/bower_components/adminbsb-materialdesign/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js'))
    ->prependFile($this->basePath('/assets/bower_components/moment/locale/pt-br.js'))
    ->prependFile($this->basePath('/assets/bower_components/moment/min/moment.min.js'))
;

$this->inlineScript()
    ->prependFile($this->basePath('/assets/js/pages/campaign.js'))
;

$class = [];
$inputs = ['name', 'period_start', 'period_final'];
foreach($inputs as $key => $input)
{
    $class[$input] = [];

    if ($this->formElementErrors($form->get($input)))
    {
        array_push($class[$input], 'error', 'focused');
    }

    if (! empty($form->get('id')->getValue()))
    {
        array_push($class[$input], 'focused');
    }

    $class[$input] = implode(' ', array_unique($class[$input]));
}
?>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Campanha</h2>
            </div>
            <div class="body">
                <?php echo $this->form()->openTag($form) . PHP_EOL; ?>
                <?php echo $this->formElement($form->get('csrf')) . PHP_EOL;?>
                <?php echo $this->formElement($form->get('id')) . PHP_EOL;?>
                <div class="row clearfix">
                    <div class="col-sm-12">
                        <div class="form-group form-float">
                            <div class="form-line <?php echo $class['name'];?>">
                                <?php echo $this->formElement($form->get('name')) . PHP_EOL;?>
                                <?php echo $this->formLabel($form->get('name')) . PHP_EOL; ?>
                            </div>
                            <?php echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<label class="error">')
                                    ->setMessageSeparatorString('</label><label class="error">')
                                    ->setMessageCloseString('</label>')
                                    ->render($form->get('name')) . PHP_EOL; ?>
                        </div>
                    </div>
                </div>
                <div class="row clearfix">
                    <div class="col-sm-6">
                        <div class="form-group form-float">
                            <div class="form-line <?php echo $class['period_start'];?>">
                                <?php echo $this->formElement($form->get('period_start')) . PHP_EOL;?>
                                <?php echo $this->formLabel($form->get('period_start')) . PHP_EOL; ?>
                            </div>
                            <?php echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<label class="error">')
                                    ->setMessageSeparatorString('</label><label class="error">')
                                    ->setMessageCloseString('</label>')
                                    ->render($form->get('period_start')) . PHP_EOL; ?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group form-float">
                            <div class="form-line <?php echo $class['period_final'];?>">
                                <?php echo $this->formElement($form->get('period_final')) . PHP_EOL;?>
                                <?php echo $this->formLabel($form->get('period_final')) . PHP_EOL; ?>
                            </div>
                            <?php echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<label class="error">')
                                    ->setMessageSeparatorString('</label><label class="error">')
                                    ->setMessageCloseString('</label>')
                                    ->render($form->get('period_final')) . PHP_EOL; ?>
                        </div>
                    </div>
                </div>
                <div class="row clearfix">
                    <div class="col-sm-12">
                        <button type="submit" class="btn bg-orange btn-lg waves-effect pull-right">SALVAR</button>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() . PHP_EOL; ?>
            </div>
        </div>
    </div>
</div>