<!-- BEGIN BREADCRUMB -->
<ol class="breadcrumb">
<?php
    /**
     * @var  $key
     * @var \Zend\Navigation\Page\Mvc $page
     */
    foreach ($this->pages as $key => $page):
?>
    <li<?php echo ($page->getActive() == true ? ' class="active"' : ''); ?>>
<?php if (! $page->getActive()): ?>
        <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel();?></a>
<?php else: ?>
        <?php echo $page->getLabel() . PHP_EOL;?>
<?php endif; ?>
    </li>
<?php
    endforeach;
?>
</ol>
<!-- END BREADCRUMB -->
