<?php
if (empty($this->pages)) {
    return;
}

$lastPageIndex = count($this->pages) - 1;
$lastPage = null;
?>
<!-- BEGIN BREADCRUMB -->
<ol class="breadcrumb">
    <li>
        <a href="<?php echo $this->url('home') ?>">Home</a>
    </li>
<?php
foreach ($this->pages as $key => $page) :
    $this->headTitle()->prepend($page->getLabel());

?>
<li <?php echo ! ($key < $lastPageIndex) ? 'class="active"' : '' ?>>
<?php if ($key < $lastPageIndex) :?>
        <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
<?php else : ?>
        <?php echo $page->getLabel() . PHP_EOL;?>
<?php endif;?>
</li>
<?php     endforeach;?>
</ol>
<!-- END BREADCRUMB -->
