<?php
/**
 * @var $container Zend\Navigation\Navigation
 * @var $page Zend\Navigation\Page\Mvc
 */
$container = $this->container;
?>
<!-- BEGIN MAIN MENU -->
<ul class="list">
    <li class="header">NAVEGAÇÃO</li>
<?php
foreach ($container as $page) :
?>
    <!-- BEGIN <?php echo strtoupper($page->getLabel());?> -->
    <li<?php if ($page->isActive()) {echo ' class="active"';} ?>>
        <a href="<?php echo $page->getHref(); ?>" class="<?php if ($page->hasPages()) {echo 'menu-toggle ';} ?>waves-effect waves-block">
<?php   if ($page->get('icon') !== '') :?>
            <i class="material-icons"><?php echo $page->get('icon'); ?></i>
<?php   endif;?>
            <span><?php echo $page->getLabel();?></span>
        </a>
<?php if ($page->hasPages()) :?>
        <ul class="ml-menu">
<?php
        foreach ($page->getPages() as $child) :
?>
            <li<?php if ($child->isActive(true)) {echo ' class="active"';} ?>>
                <a href="<?php echo $child->getHref() ?>"><?php echo $child->getLabel();?></a>
            </li>
<?php
        endforeach;
?>
        </ul>
<?php endif;?>
    </li>
    <!-- END <?php echo strtoupper($page->getLabel());?> -->
<?php
endforeach;
?>
</ul>
<!-- END MAIN MENU -->
